const AСTypes = {
  AUTH: "AUTH",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  USER_ROLE: "USER_ROLE",
  SHOW_USERS_LIST: "SHOW_USERS_LIST",

  ALL_ENTRIES: "ALL_ENTRIES",
  ADD_ENTRY: "ADD_ENTRY",
  EDIT_ENTRY: "EDIT_ENTRY",
  DELETE_ENTRY: "DELETE_ENTRY",
  LIKE_ENTRY: "LIKE_ENTRY",

  MAP: "MAP",
  POINT: "POINT", // позиция по клику

  CURRENT_IMG: "CURRENT_IMG",
  CURRENT_IMG_USER: "CURRENT_IMG_USER",
  CURRENT_IMG_CLEAR: "CURRENT_IMG_CLEAR",
  GET_IMG: "GET_IMG",
  SET_IMG: "SET_IMG",

  ALL_COMMENTS: "ALL_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  LOADING_COMMENTS: "LOADING_COMMENTS",
  DELETE_COMMENT: "DELETE_COMMENT",
};

export default AСTypes;
