const AСTypes = {
  AUTH: "AUTH",
  USER_ROLE: "USER_ROLE",
  ALL_ENTRIES: "ALL_ENTRIES",
  ADD_ENTRY: "ADD_ENTRY",
  EDIT_ENTRY: "EDIT_ENTRY",
  LIKE_ENTRY: "LIKE_ENTRY",

  MAP: "MAP",

  CURRENT_IMG: "CURRENT_IMG",
  ALL_COMMENTS: "ALL_COMMENTS",
};

export default AСTypes;
