const AСTypes = {
  AUTH: "AUTH",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  USER_ROLE: "USER_ROLE",
  SHOW_USERS_LIST: "SHOW_USERS_LIST",

  ALL_ENTRIES: "ALL_ENTRIES",
  ADD_ENTRY: "ADD_ENTRY",
  EDIT_ENTRY: "EDIT_ENTRY",
  DELETE_ENTRY: "DELETE_ENTRY",
  LIKE_ENTRY: "LIKE_ENTRY",
  CURRENT_IMG: "CURRENT_IMG",

  MAP: "MAP",
  POINT: "POINT", // позиция по клику
  CURRENT_IMG_MAP: 'CURRENT_IMG_MAP',
  CONFIRM_POINT:'CONFIRM_POINT',
  
  ALL_COMMENTS: "ALL_COMMENTS",
  ADD_COMMENT: "ADD_COMMENT",
  LOADING_COMMENTS: "LOADING_COMMENTS",
  DELETE_COMMENT: "DELETE_COMMENT",
};

export default AСTypes;
